name: Check
on:
  push: {}
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 8 * * *"
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "^1.18.2"
          - "^1.17.5"
          - "1.17.5"
          - "1.16.12"
          - "1.15.15"
        stable:
          - true
        may-fail:
          - false
    continue-on-error: ${{ matrix.may-fail }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go }}"
          stable: ${{ matrix.stable }}
      - run: go version
      - run: go build -v ./...
      - run: go test -race -parallel 4 -timeout 30s -v ./...
  Staticchek:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"
      - run: |
          unformatted=$(gofmt -l .)
          if [[ ! -z "$unformatted" ]]; then
            echo "Files need formatting!"
            echo $unformatted
            exit 1
          fi
  Vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"
      - run: go vet ./...
