name: Manual
on:
  push:
    branches:
      - mobilarte
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "^1.18.3"
        stable:
          - true
        may-fail:
          - false
    continue-on-error: ${{ matrix.may-fail }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go }}"
          stable: ${{ matrix.stable }}
      - run: go version
      - run: go build -v ./...
      - run: go test -race -parallel 4 -timeout 30s -v ./...
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18.3"
      - run: |
          unformatted=$(gofmt -l .)
          if [[ ! -z "$unformatted" ]]; then
            echo "Files need formatting!"
            echo $unformatted
            exit 1
          fi
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
  Vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18.3"
      - run: go vet ./...
